services:
  pytest:
    build: ./main
    volumes:
      - type: bind
        source: ./
        target: /tests
        read_only: true
      - type: tmpfs
        target: /tmp
    environment:
      TMPDIR: /tmp
    depends_on:
      - rest
    command:
      - "true"
    networks:
      main:

  rest:
    build: ./rest/
    expose:
      - "5000"
    networks:
      main:
        aliases:
          - alternate-rest

networks:
  main:
